social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: GitHub
    link: https://github.com/zzugzj
    icon: icon-github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:10456430552@qq.com
    icon: icon-mail-line
    color: '#8E71C1'
local_search:
  enable: true
banner:
  enable: true
  title: è«åœ¨æµ®æ²™ç­‘é«˜å°
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜Š
    message: ç–¯ç‹‚Coding...

menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: icon-cloud-line
    #   count: ä½ çŒœ
  custom:
    title: æ–‡æ¡£
    path: https://zzugzj.github.io
    icon: icon-settings-line
comment:
  candidates:
    - waline
    - twikoo
    # - giscus
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/zzugzj/zzugzj.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚

waline:
  enable: true
  serverURL: https://zzugzj.github.io
  visitor: true
  comment: true
  emoji:
    - "@waline/emojis@latest/bilibili/"
    - "@waline/emojis@latest/weibo/"
    - "@waline/emojis@latest/qq/"
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: [nick]

twikoo:
  enable: true
  envId: test-1c8fe2
github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: gzj
  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

giscus:
  enable: false
  repo: YunYouJun/yunyoujun.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

engine_search:
  enable: false
local_search:
  enable: true
  # ...

google_analytics:
  enable: true
  id: G-1LL0D86CY9
iconify:
  global: true
medium_zoom: true
google_adsense:
  enable: true
  client: ca-pub-2245427233262012
google_tagmanager:
  enable: true
  id: GTM-M9KWR9L
wordcount:
  enable: true
post_edit:
  enable: false
cursor:
  enable: true
baidu_push: true
albums:
  enable: true
pages:
post_meta:
  item_text: true
types:
  link:
    color: blue
    icon: icon-external-link-line
  github:
    color: black
    icon: icon-github-line
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: true  # æ˜¯å¦åœ¨å¤åˆ¶æ–‡ç« æ—¶ï¼Œåœ¨å‰ªè´´æ¿ä¸­è¿½åŠ ç‰ˆæƒä¿¡æ¯
say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn
# åœ¨æ¯å¹´çš„æŒ‡å®šæ—¥æœŸï¼Œå¼€å¯ç°è‰²é»˜å“€æ¨¡å¼ã€‚
mourn:
  enable: true
  days:
    - 4-4
reward:
  enable: true
  icon: icon-hand-coin-line
  comment: I'm so cute. Please give me money.
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: https://raw.githubusercontent.com/zzugzj/blogImg/master/github/image-20231105142404489.png
      color: '#00A3EE'
      icon: icon-alipay-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://raw.githubusercontent.com/zzugzj/blogImg/master/github/image-20231105142333140.png
      color: '#2DC100'
      icon: icon-wechat-pay-line
footer:
  since: 2021
  powered:
    enable: false
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: '2021-01-01T00:00:00'
  support:
    enable: true
    title: GitHub
    link: https://github.com/
    logo: https://raw.githubusercontent.com/zzugzj/blogImg/master/github/github-mark.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾›ä»£ç æ‰˜ç®¡